apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
type: Opaque
stringData:
  AUTH0_CALLBACK_URL: http://localhost:8080/callback
  AUTH0_CLIENT_ID: id
  AUTH0_CLIENT_SECRET: secrer
  AUTH0_DOMAIN: dev-kcfug7811noq.us.auth0.com
  AUTH0_AUDIENCE: https://bookinfo.io
